stages:
  - test

before_script:
  - >-
    [ ! -d "__GOPATH" ] &&
    mkdir -p "__GOPATH/src/gitlab.alexhamlin.co/$CI_PROJECT_NAMESPACE" &&
    ln -s "$(pwd)" "__GOPATH/src/gitlab.alexhamlin.co/$CI_PROJECT_PATH"
  - export GOPATH="$(pwd)/__GOPATH"

test:
  stage: test
  script:
    - 'go version'
    - 'go test gitlab.alexhamlin.co/$CI_PROJECT_PATH/slackio -cover -timeout 10s -race'
