language: go
go:
  - '1.11'

script:
  - env GO111MODULE=on make release
  - ./slackbridge-linux-amd64 --version

deploy:
  provider: releases
  api_key:
    secure: CvtZeByqg89ShA52BsKM/gRbQLakE+1TpVYuUSkxeJyfDDJ+Fz76tzxPNoLCN05hYc9KLc8be8q2vq82Ig0O37eOAOWSkgalnBoZLyc55rER4RxbOgqThGP/raxqsff7sC+TATJB4lwzC8u47EckXYs3pxomZzMCTwgtArnBr6vKXIYQG0F/Oj2IhBeA4eJIV7P4saAt1TA6YNl1mv7GcltrTkcRdz13l0zB8AMWEaNJBOWLF/trkK3/RY9+IpF4dDz8H/Oee1E+BxToJbbMAYYZJkxUhEsSuSR/eY3qrhrlPs9EXL8bSnSghPfK/XJMsso1qyU5hAUx5bN+TkmJhtWaWhr1LgEeydgIARyLVFQV+XLSG9XhsDyz2SOyrCqw/CIggARuyhrhf26uJ1F1C2kMMXr8LyY8K/UfrcyLUUXO9xlEBljwYg1e05F0eRmCbAirlwlPNX0aifvuyc453SjcbKXHEuGmCCHcAeZsQEIPUIjLb+FAvtk6BDiCG3RgEkE3aX76o5Znb28CfXPxwu1eMDoDtldki5CNdzc9GDX6L7nHPpEXKk14c50toggVmFme+gWAigmMPHubmF4lERTCoU1S6rTulp7SLWqqYQJfab6D8SVYmcdmnPhZoJw90j8HZ+C6YRF6bVMeR6baXSoopUeBIXrY530BihOgTSY=
  file:
    - slackbridge-linux-amd64
  skip_cleanup: true
  on:
    tags: true
